services:
  - type: web
    name: jyotish-api
    runtime: python
    rootDir: astrology/astrology-api
    plan: free
    buildCommand: "pip install -r requirements.txt && python download_ephe.py"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port 10000"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
